# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cabd3b37d5e74e0e3571b5d24644fe38c5aa1b8e3056ea94e40eee69498877c8198ea1d2f4912779962f5b027a848921a32f044ccc5c15e51854a5a35851d3a

test:
  secret_key_base: 7cc41bbf378d9b487e67fac405df0a1bcc5c2c78b9b3167aa671c9a7cb3087c36a71264ddabc8d940b28d406cbd7d38ab101b724d23247eab11e2ba6716ad55f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
